# Get the base image 
FROM node:16-alpine


#  Change to working directory 
WORKDIR '/app'


# Install some dependencties
COPY package.json .
RUN npm install


# Copy the rest of the source 
COPY . .

# Setup the start-up command 
CMD ["npm", "run", "start"]
